name: Deploy to s3

on:
  push:
    branches: [main]
  # pull_request:

jobs:
  s3-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: git clone the repo
        run: git clone https://github.com/royalteegee/welcome-app.git
      - name: copy the files to s3
        run: aws s3 sync ./welcome-app s3://smarthub-testing